/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : LCD1.c
**     Project     : ProcessorExpert
**     Processor   : MKL25Z128VLK4
**     Component   : LCDHTA
**     Version     : Component 01.002, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2012-12-22, 22:18, # CodeGen: 35
**     Abstract    :
**          This component implements a driver for multiple 2x16 character displays.
**     Settings    :
**          Component name                                 : LCD1
**          HW Interface                                   : 
**            LCD Type                                     : generic
**            LCD Lines                                    : 2
**            LCD Enable Signal                            : Disabled
**            Read from Display                            : Enabled
**              R/W signal                                 : CtrlPin
**              Check Busy Flag                            : yes
**            Wait (us)                                    : 0
**            E signal                                     : CtrlPin
**            RS signal                                    : CtrlPin
**            Data/Control Bus                             : 
**              Data/Control Bus Width                     : 4bit
**              DB0..DB3                                   : Disabled
**              DB4..DB7                                   : Enabled
**                DB4                                      : DBpin
**                DB5                                      : DBpin
**                DB6                                      : DBpin
**                DB7                                      : DBpin
**              Bits/Byte Bus                              : Disabled
**          System Interface                               : 
**            Wait                                         : WAIT1
**     Contents    :
**         Write        - void LCD1_Write(char ch);
**         WriteLn      - void LCD1_WriteLn(void);
**         WriteLineStr - void LCD1_WriteLineStr(uint8_t line, char *str);
**         WriteString  - void LCD1_WriteString(char *str);
**         ShiftLeft    - void LCD1_ShiftLeft(void);
**         ShiftRight   - void LCD1_ShiftRight(void);
**         GotoXY       - void LCD1_GotoXY(uint8_t line, uint8_t column);
**         SetEntryMode - void LCD1_SetEntryMode(bool increment, bool shiftLeft);
**         Home         - void LCD1_Home(void);
**         Line         - void LCD1_Line(uint8_t line);
**         Clear        - void LCD1_Clear(void);
**
**     License   :  Open Source (LGPL)
**     Copyright : (c) Copyright Erich Styger, 2012, all rights reserved.
**     http      : www.mcuoneclipse.com
**     This an open source software implementing software using Processor Expert.
**     This is a free software and is opened for education,  research  and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/

/* MODULE LCD1. */
#include "LCD1.h"

/* DEFINES for display commands.
   See as well www.freescale.com/files/microcontrollers/doc/app_note/AN1745.pdf
   for additional details.
*/
#define ClearDisplayCmd                   0x01 /* clears the display */

#define ReturnHomeCmd                     0x02 /* moves the cursor to the beginning of the first line */

#define EntryModeSetCmd                   0x04
#define EntryModeSet_ShiftOn              1 /* S flag: shift display */
#define EntryModeSet_IncrementOn          2 /* I/D flag: increment cursor */

#define DisplayOnOffControlCmd            0x08 /* Display on/off control command. There are 3 bits D, C and B as well */
#define DisplayOnOffControl_BlinkOn       1 /* B flag: blinking cursor on/off; B=1 blinking, B=0 not blinking */
#define DisplayOnOffControl_CursorOn      2 /* C flag: cursor on/off, C=1 cursor on, C=0 cursor off */
#define DisplayOnOffControl_DisplayOn     4 /* D flag: display on/off, D=1 display on, D=0 display off */

#define FunctionSetCmd          0x20
#define FunctionSet_8bit        0x10 /* DL flag: DL=1: 8bit, DL=0: 4bit */
#define FunctionSet_4bit        0 /* DL flag: DL=1: 8bit, DL=0: 4bit */
#define FunctionSet_2Lines      0x08 /* N flag: number of display lines: N=1 2 lines, N=0 1 line */
#define FunctionSet_1Line       0 /* N flag: number of display lines: N=1 2 lines, N=0 1 line */
#define FunctionSet_Font5x10    0x04 /* F flag: character font, F=1 5x10 dots, F=0 5x8 dots */
#define FunctionSet_Font5x8     0 /* F flag: character font, F=1 5x10 dots, F=0 5x8 dots */

#define CursorOnCmd    (DisplayOnOffControlCmd|DisplayOnOffControl_DisplayOn|DisplayOnOffControl_CursorOn)
#define CursorOffCmd   (DisplayOnOffControlCmd|DisplayOnOffControl_DisplayOn)
#define GotoXYCmd      0x80
#define Line2Offset    0x40
#define FirstLineCmd   (GotoXYCmd)
#define SecondLineCmd  (GotoXYCmd + Line2Offset)

#define RightShiftCmd   0x1C
#define LeftShiftCmd    0x18

#define BusyFlag       0x80 /* BF Flag */

/* support for custom soft characters in the display which can be used with LCD1_LoadSoftChar() */
const uint8_t LCD1_SoftCharUE[8] = { /* ü */
  0x11, 0x00, 0x11, 0x11, 0x11, 0x13, 0x0d, 0
/* X...X
   .....
   X...X
   X...X
   X...X
   X..XX
   .XX.X */
};

const uint8_t LCD1_SoftCharAE[8] = { /* ä */
  0x11, 0x00, 0x0E, 0x01, 0x0F, 0x11, 0x0F, 0
/* X...X
   .....
   .XXX.
   ....X
   .XXXX
   X...X
   .XXXX */
};

const uint8_t LCD1_SoftCharOE[8] = { /* ö */
  0x11, 0x00, 0x0E, 0x11, 0x11, 0x11, 0x0E, 0
/* X...X
   .....
   .XXX.
   X...X
   X...X
   X...X
   .XXX. */
};

/* macros for the RS pin */
#define ClrRS() \
        GPIO_WriteBit(LCD_PORT, LCD_RS, Bit_RESET);   /* RS=0: command mode */
#define SetRS() \
        GPIO_WriteBit(LCD_PORT, LCD_RS, Bit_SET);   /* RS=1: data mode */

/* macros for the EN pin */
#define ClrEN() \
        GPIO_WriteBit(LCD_PORT, LCD_EN, Bit_RESET);   /* EN=0 */
#define SetEN() \
        GPIO_WriteBit(LCD_PORT, LCD_EN, Bit_SET);   /* EN=1 */

static uint8_t DataGet(void) 
{
  uint8_t val;

  val =  (GPIO_ReadInputDataBit(LCD_PORT, LCD_D7)<<3)
        |(GPIO_ReadInputDataBit(LCD_PORT, LCD_D6)<<2)
        |(GPIO_ReadInputDataBit(LCD_PORT, LCD_D5)<<1)
        |(GPIO_ReadInputDataBit(LCD_PORT, LCD_D4)<<0);
  return val;
}

static void DataPut(uint8_t val) 
{
  GPIO_WriteBit(LCD_PORT, LCD_D7, (val&(1<<3))!=0);
  GPIO_WriteBit(LCD_PORT, LCD_D6, (val&(1<<2))!=0);
  GPIO_WriteBit(LCD_PORT, LCD_D5, (val&(1<<1))!=0);
  GPIO_WriteBit(LCD_PORT, LCD_D4, (val&(1<<0))!=0);
}

/* Internal method prototypes */
static void EnablePulse(void);
static void WriteLCDCommand(uint8_t cmd);

/*
** ===================================================================
**     Method      :  EnablePulse (component LCDHTA)
**
**     Description :
**         Creates a pulse to transfer data and/or commands
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void EnablePulse(void)
{
  SetEN();                              /* set EN to 1 to create pulse */
  Delay_ms(1);
  ClrEN();                              /* set to 0 to finish pulse */
}

/*
** ===================================================================
**     Method      :  WriteLCDCommand (component LCDHTA)
**
**     Description :
**         Writes a command to the display
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void WriteLCDCommand(uint8_t cmd)
{
  /* 2 4bit transfer */
  DataPut((uint8_t)((cmd&0xF0)>>4));       /* Write the data (cycle #1) */
  EnablePulse();                        /* transfer data */
  Delay_ms(1);
  DataPut((uint8_t)(cmd&0x0F) );           /* Write the data (cycle #2) */
  EnablePulse();                        /* do the command transfer */
  Delay_ms(1);
}

/*
** ===================================================================
**     Method      :  LCD1_Clear (component LCDHTA)
**
**     Description :
**         Clears the display and moves the cursor to the first line.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void LCD1_Clear(void)
{
  WriteLCDCommand(ClearDisplayCmd);     /* send the clear command to the LCD */
}

/*
** ===================================================================
**     Method      :  LCD1_Home (component LCDHTA)
**
**     Description :
**         Moves the cursor to the beginning of the first line.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void LCD1_Home(void)
{
  WriteLCDCommand(ReturnHomeCmd);       /* moves the cursor to the beginning of the first line */
}

/*
** ===================================================================
**     Method      :  LCD1_WriteLCDData (component LCDHTA)
**
**     Description :
**         Writes data to the display
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void LCD1_WriteLCDData(uint8_t ch)
{
   SetRS();                             /* RS = 1: data mode */
   /* 2 4bit transfer */
   DataPut((uint8_t)((ch&0xF0)>>4));       /* Write the data (cycle #1) */
   EnablePulse();                       /* transfer data */
   Delay_ms(1);
   DataPut((uint8_t)(ch&0x0F));            /* Write the data (cycle #2) */
   EnablePulse();                       /* do the command transfer */
   Delay_ms(1);
   ClrRS();                             /* RS = 0: back to command mode */
}

/*
** ===================================================================
**     Method      :  LCD1_GotoXY (component LCDHTA)
**
**     Description :
**         Places the cursor on a specified position on the display.
**     Parameters  :
**         NAME            - DESCRIPTION
**         line            - Line number starting with 1
**         column          - Column number starting with 1
**     Returns     : Nothing
** ===================================================================
*/
void LCD1_GotoXY(uint8_t line, uint8_t column)
{
/* row is in the range 1..LCD_Nof_Lines and column in the range 1..LCD_Nof_Columns */
  WriteLCDCommand((uint8_t)(GotoXYCmd + (column-1) + (line==1 ? 0x00:Line2Offset)));
}

/*
** ===================================================================
**     Method      :  LCD1_ShiftLeft (component LCDHTA)
**
**     Description :
**         Shifts all characters to the left.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void LCD1_ShiftLeft(void)
{
  WriteLCDCommand(LeftShiftCmd);
}

/*
** ===================================================================
**     Method      :  LCD1_Write (component LCDHTA)
**
**     Description :
**         Write a single character to the display
**     Parameters  :
**         NAME            - DESCRIPTION
**         ch              - Character to write
**     Returns     : Nothing
** ===================================================================
*/
/* The method is implemented as a macro, see LCD1.h */
/*
** ===================================================================
**     Method      :  LCD1_WriteLn (component LCDHTA)
**
**     Description :
**         Writes a new line to the display
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void LCD1_WriteLn(void)
{
  WriteLCDCommand(SecondLineCmd);
}

/*
** ===================================================================
**     Method      :  LCD1_WriteString (component LCDHTA)
**
**     Description :
**         Writes a string to the display at the current cursor
**         position.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * str             - Pointer to string (zero byte terminated)
**                           to write to the display
**     Returns     : Nothing
** ===================================================================
*/
void LCD1_WriteString(char *str)
{
  while (*str != '\0'){
    LCD1_Write(*str);
    str++;
  }
}

/*
** ===================================================================
**     Method      :  LCD1_WriteLineStr (component LCDHTA)
**
**     Description :
**         Writes a full line to the display (clears the rest of the
**         line).
**     Parameters  :
**         NAME            - DESCRIPTION
**         line            - Line number (starting with 1).
**       * str             - Pointer to the string which should be
**                           shown on the display.
**     Returns     : Nothing
** ===================================================================
*/
void LCD1_WriteLineStr(uint8_t line, char *str)
{
  uint8_t i;

  LCD1_Line(line);                      /* select line */
  for(i = 0; i < LCD1_MAX_LCD_LINE_CHARS && *str!='\0'; i++, str++) {
    LCD1_Write(*str);
  }
  /* Clear the rest of the line */
  for (; i < LCD1_MAX_LCD_LINE_CHARS; i++) {
    LCD1_Write(' ');
  }
}

/*
** ===================================================================
**     Method      :  LCD1_Line (component LCDHTA)
**
**     Description :
**         Sets the current line.
**     Parameters  :
**         NAME            - DESCRIPTION
**         line            - Line number, starting with 1
**     Returns     : Nothing
** ===================================================================
*/
void LCD1_Line(uint8_t line)
{
  WriteLCDCommand((uint8_t)(line==1?FirstLineCmd:SecondLineCmd));
}

/*
** ===================================================================
**     Method      :  LCD1_Init (component LCDHTA)
**
**     Description :
**         Display driver initialization routine.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void LCD1_Init(void)
{
    GPIO_InitTypeDef GPIO_InitStructure;

    /* Enable the GPIO_LED Clock */
    RCC_APB2PeriphClockCmd(LCD_CLK, ENABLE);

    /* Configure the GPIO_LED pin */
    GPIO_InitStructure.GPIO_Mode = GPIO_Mode_Out_PP;
    GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
    
    GPIO_InitStructure.GPIO_Pin = LCD_RS;
    GPIO_Init(LCD_PORT, &GPIO_InitStructure);
    GPIO_InitStructure.GPIO_Pin = LCD_EN;
    GPIO_Init(LCD_PORT, &GPIO_InitStructure);
    GPIO_InitStructure.GPIO_Pin = LCD_D7;
    GPIO_Init(LCD_PORT, &GPIO_InitStructure);
    GPIO_InitStructure.GPIO_Pin = LCD_D6;
    GPIO_Init(LCD_PORT, &GPIO_InitStructure);
    GPIO_InitStructure.GPIO_Pin = LCD_D5;
    GPIO_Init(LCD_PORT, &GPIO_InitStructure);
    GPIO_InitStructure.GPIO_Pin = LCD_D4;
    GPIO_Init(LCD_PORT, &GPIO_InitStructure);

    /* This function initializes the driver.
     The low level init already shall have set our data port to input/output, currently set to output,
     plus all control pins are set as outputs with low values. To be sure, we do it here again. */
    ClrEN();                              /* EN Pin low */
    //ClrRW();                              /* RW Pin low */
    ClrRS();                              /* RS Pin low: command mode */
    DataPut(0);

    /* make pins output */
    //DataAsOutput();

    /* send the reset sequence according to the data sheet */
    Delay_ms(1);                           /* wait for more than 15ms after Vcc rises to 4.5V, wait for more than 40ms after Vcc rises to 2.7V. In case of POR (Power On Reset) we need some additional time. */
    DataPut(0x3);                         /* BF cannot be checked before this function, function set (interface is 8bits long) */
    EnablePulse();                        /* transfer data */
    Delay_ms(1);                            /* wait for more than 4.1 ms */
    /* 0x3 is already on the bus from previous DataPut(), do not need to put it again here */
    EnablePulse();                        /* transfer data */
    Delay_ms(1);                          /* wait for more than 100us */
    /* 0x3 is already on the bus from previous DataPut(), do not need to put it again here */
    EnablePulse();                        /* transfer data */
    Delay_ms(1);                          /* wait for more than 100us */

    DataPut(0x2);                         /* Function set */
    EnablePulse();                        /* transfer data */
    Delay_ms(1);

    WriteLCDCommand(FunctionSetCmd|FunctionSet_Font5x8
             |FunctionSet_4bit      /* we are using 4bit data bus */ \
             |FunctionSet_2Lines    /* we are using two lines */
             );
    WriteLCDCommand(DisplayOnOffControlCmd|DisplayOnOffControl_DisplayOn);
    WriteLCDCommand(ClearDisplayCmd); /* Clear display */
    WriteLCDCommand(EntryModeSetCmd|EntryModeSet_IncrementOn); /* Entry mode set: Increment mode, display shift off */
}

/*
** ===================================================================
**     Method      :  LCD1_ShiftRight (component LCDHTA)
**
**     Description :
**         Shifts all characters to the right.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void LCD1_ShiftRight(void)
{
  WriteLCDCommand(RightShiftCmd);
}

/*
** ===================================================================
**     Method      :  LCD1_SetEntryMode (component LCDHTA)
**
**     Description :
**         Configures the display entry mode, if the cursor has to
**         shift and/or if the display shall shift content while
**         displaying text.
**     Parameters  :
**         NAME            - DESCRIPTION
**         increment       - Increments (TRUE) or
**                           decrements (FALSE) the display address by 1
**                           when a character code is written into or
**                           read from DDRAM. The cursor or blinking
**                           moves to the right when incremented by 1
**                           and to the left when decremented by 1.
**         shiftLeft       - The display does not shift if
**                           the 'shift' is FALSE. If 'shift' is TRUE,
**                           it will seem as if the cursor does not move
**                           but the display does.
**     Returns     : Nothing
** ===================================================================
*/
void LCD1_SetEntryMode(bool increment, bool shiftLeft)
{
  uint8_t flags = 0;

  if (increment) {
    flags |= EntryModeSet_IncrementOn;
  }
  if (shiftLeft) {
    flags |= EntryModeSet_ShiftOn;
  }
  WriteLCDCommand((uint8_t)(EntryModeSetCmd|flags)); /* Entry mode set: Increment mode, display shift mode */
}

/* END LCD1. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 10.0 [05.03]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
